# Generated by Django 3.2.7 on 2021-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORY_TABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, default='', max_length=100000000000)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('total_jumps', models.CharField(blank=True, default=0, max_length=100000000000)),
            ],
        ),
        migrations.CreateModel(
            name='RIGTABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, default='', max_length=100000000000, verbose_name='Barcode')),
                ('packed_count', models.CharField(blank=True, default='', max_length=100000000000, verbose_name='Packed Count')),
                ('container_and_harness', models.CharField(blank=True, default='', max_length=100000000000, verbose_name='Container and Harness')),
                ('main_canopy_line_set', models.CharField(blank=True, default='', max_length=100000000000, verbose_name='Main Canopy Line Set')),
                ('main_canopy', models.CharField(blank=True, default='', max_length=100000000000, verbose_name='Main Canopy')),
                ('d_bag', models.CharField(blank=True, default='', max_length=100000000000, verbose_name='D Bag')),
                ('pilot_chute_and_bridle', models.CharField(blank=True, default='', max_length=100000000000, verbose_name='Pilot Chute/Drogue and Bridle’')),
                ('last_unit', models.IntegerField(blank=True, default=50)),
                ('sort_key1', models.CharField(blank=True, default=0, max_length=100)),
                ('sort_key2', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TEMP_TABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, default='', max_length=100000000000)),
                ('total_jumps', models.CharField(blank=True, default=0, max_length=100000000000)),
            ],
        ),
    ]
