# Generated by Django 3.2.7 on 2021-10-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HISTORY_TABLE',
        ),
        migrations.DeleteModel(
            name='TEMP_TABLE',
        ),
    ]
