# Generated by Django 3.2.7 on 2021-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20211008_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORY_TABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, default='', max_length=100000000000)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_jumps', models.CharField(blank=True, default=0, max_length=100000000000)),
            ],
        ),
        migrations.CreateModel(
            name='TEMP_TABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, default='', max_length=100000000000)),
                ('total_jumps', models.CharField(blank=True, default=0, max_length=100000000000)),
            ],
        ),
    ]
