# Generated by Django 3.2.8 on 2021-11-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_history_table_temp_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rigtable',
            name='last_unit',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
