# Generated by Django 3.2.8 on 2022-01-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_alter_rigtable_last_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigtable',
            name='hundred_mod_unit',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
